volumes:
  postgres_data:
    driver: "local"
  maven_cache:

networks:
  wise_network:
    driver: "bridge"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_stock_wise_compose
    restart: always
    environment:
      - POSTGRES_DB=stock_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=America/Sao_Paulo
    ports:
      - "5435:5432"
    networks:
      - wise_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11-alpine
    container_name: rabbitmq_product
    environment:
      RABBITMQ_DEFAULT_USER: wise
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5673:5672"
      - "15673:15672"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: stock_wise_backend_compose
    volumes:
      - maven_cache:/root/.m2
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8088:8080"
    networks:
      - wise_network